#!/usr/bin/env python2
import os, sys
sys.path.insert(0, '.deps/flockutil')
sys.path.insert(0, '.deps/cuburn')
if 'FLOCK_PATH' in os.environ:
    for p in reversed(os.environ['FLOCK_PATH'].split(':')):
        sys.path.insert(0, p)
import flockutil.main
flockutil.main.main()
